---
- name: Remove legacy Docker apt source if present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  failed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - psmisc
      - rsync
      - ufw
    state: present

- name: Configure UFW - allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Configure UFW - allow HTTP
  community.general.ufw:
    rule: allow
    port: "{{ traefik_http_port | default(80) }}"
    proto: tcp

- name: Configure UFW - allow HTTPS
  community.general.ufw:
    rule: allow
    port: "{{ traefik_https_port | default(443) }}"
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    logging: on
  register: ufw_enabled
  failed_when: false
