name: ${COMPOSE_PROJECT_NAME:-cia-app}

services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MARIADB_DATABASE: ${DB_NAME:-dev_db}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mariadb-admin ping -h 127.0.0.1 -p${DB_PASSWORD:-root} || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 30
    restart: unless-stopped
    networks:
      - app-network

  api:
    build:
      context: ./back_student
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-dev_db}
      NODE_ENV: ${NODE_ENV:-production}
      PYTHON: ${PYTHON:-/usr/bin/python3}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "${API_PORT:-3000}"
    labels:
      - logging=promtail
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: ./front_student
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
        - nginx:1.27-alpine
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-/api}
    depends_on:
      - api
    ports:
      - "${WEB_PORT:-8080}:80"
    labels:
      - logging=promtail
    restart: unless-stopped
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/config.yml:ro
    environment:
      LOKI_URL: ${LOKI_URL:-http://host.docker.internal:3100/loki/api/v1/push}
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: