http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  routers:
    http-catchall:
      rule: HostRegexp()
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal
