global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: critical-receiver
    continue: true
  - match:
      severity: warning
    receiver: warning-receiver
    continue: true

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'
    send_resolved: true

- name: 'critical-receiver'
  webhook_configs:
  - url: 'http://localhost:5001/critical'
    send_resolved: true

- name: 'warning-receiver'  
  webhook_configs:
  - url: 'http://localhost:5001/warning'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']