version: "3.9"
name: cia-ops

x-user: &user "1001:1001"

services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    ports: ["${LOKI_PORT:-3100}:3100"]
    environment:
      LOKI_RETENTION_PERIOD: ${LOKI_RETENTION_PERIOD:-168h}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-GrafanaAdmin2025!}
      GF_INSTALL_PLUGINS: ${GRAFANA_INSTALL_PLUGINS:-}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: ["${GRAFANA_PORT:-3000}:3000"]
    depends_on: [loki]
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.20.3
    environment:
      PORTAINER_ADMIN_PASSWORD: ${PORTAINER_ADMIN_PASSWORD:-PortainerAdmin2025!}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports: ["${PORTAINER_PORT:-9000}:9000"]
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:
  portainer-data: