name: cia-ops

x-user: &user "1001:1001"

services:
  traefik:
    image: traefik:v3.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "9100:9100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    restart: unless-stopped
    networks:
      - traefik
      - prometheus
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    # No direct port mapping; reachable via internal networks
    environment:
      LOKI_RETENTION_PERIOD: ${LOKI_RETENTION_PERIOD:-168h}
    restart: unless-stopped
    networks:
      - traefik

  grafana:
    image: grafana/grafana:10.2.3
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-GrafanaAdmin2025!}
      GF_INSTALL_PLUGINS: ${GRAFANA_INSTALL_PLUGINS:-}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on: [loki]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - traefik
      - prometheus

  portainer:
    image: portainer/portainer-ce:2.20.3
    environment:
      PORTAINER_ADMIN_PASSWORD: ${PORTAINER_ADMIN_PASSWORD:-PortainerAdmin2025!}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - traefik

  gitea:
    image: gitea/gitea:1.22-rootless
    environment:
      - USER_UID=${GITEA_USER_UID:-1000}
      - USER_GID=${GITEA_USER_GID:-1000}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=${GITEA_DB_NAME:-gitea}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD:-GiteaPassword123!}
      - GITEA__server__DOMAIN=gitea.localhost
      - GITEA__server__SSH_DOMAIN=gitea.localhost
      - GITEA__server__ROOT_URL=https://gitea.localhost:${TRAEFIK_HTTPS_PORT:-443}/
      - GITEA__server__HTTP_PORT=${GITEA_HTTP_PORT:-3000}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT:-2222}
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY:-changeme-secret-key-minimum-64-chars-aaaaaaaaaaaaaaaaaaaaaaaaaaaa}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN:-changeme-internal-token-minimum-64-chars-bbbbbbbbbbbbbbbbbbbbbbbb}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION:-false}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN:-false}
      - GITEA__admin__DEFAULT_THEME=${GITEA_THEME:-arc-green}
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_SSH_PORT:-2222}:22" # Keep SSH exposed
    depends_on:
      gitea-db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.gitea.rule=Host(`gitea.localhost`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls=true
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.routers.gitea.middlewares=gitea-headers
      - traefik.http.middlewares.gitea-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.gitea-headers.headers.customrequestheaders.X-Forwarded-Host=gitea.localhost
    networks:
      - traefik

  gitea-db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${GITEA_DB_ROOT_PASSWORD:-GiteaRootPassword123!}
      - MARIADB_DATABASE=${GITEA_DB_NAME:-gitea}
      - MARIADB_USER=${GITEA_DB_USER:-gitea}
      - MARIADB_PASSWORD=${GITEA_DB_PASSWORD:-GiteaPassword123!}
    volumes:
      - gitea-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p${GITEA_DB_ROOT_PASSWORD:-GiteaRootPassword123!} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped
    networks:
      - traefik

  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - prometheus

volumes:
  loki-data:
  grafana-data:
  portainer-data:
  gitea-data:
  gitea-db-data:

networks:
  traefik:
    external: true
  prometheus:
    driver: bridge
