version: "3.9"
name: cia-ops

x-user: &user "1001:1001"

services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    ports: ["${LOKI_PORT:-3100}:3100"]
    environment:
      LOKI_RETENTION_PERIOD: ${LOKI_RETENTION_PERIOD:-168h}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-GrafanaAdmin2025!}
      GF_INSTALL_PLUGINS: ${GRAFANA_INSTALL_PLUGINS:-}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: ["${GRAFANA_PORT:-3000}:3000"]
    depends_on: [loki]
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.20.3
    environment:
      PORTAINER_ADMIN_PASSWORD: ${PORTAINER_ADMIN_PASSWORD:-PortainerAdmin2025!}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports: ["${PORTAINER_PORT:-9000}:9000"]
    restart: unless-stopped

  gitea:
    image: gitea/gitea:1.22-rootless
    environment:
      - USER_UID=${GITEA_USER_UID:-1000}
      - USER_GID=${GITEA_USER_GID:-1000}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=${GITEA_DB_NAME:-gitea}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD:-GiteaPassword123!}
      - GITEA__server__DOMAIN=${GITEA_DOMAIN:-localhost}
      - GITEA__server__SSH_DOMAIN=${GITEA_DOMAIN:-localhost}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL:-http://localhost:3001}
      - GITEA__server__HTTP_PORT=${GITEA_HTTP_PORT:-3000}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT:-2222}
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY:-changeme-secret-key-minimum-64-chars-aaaaaaaaaaaaaaaaaaaaaaaaaaaa}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN:-changeme-internal-token-minimum-64-chars-bbbbbbbbbbbbbbbbbbbbbbbb}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION:-false}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN:-false}
      - GITEA__admin__DEFAULT_THEME=${GITEA_THEME:-arc-green}
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT:-3001}:3000"
      - "${GITEA_SSH_PORT:-2222}:22"
    depends_on:
      gitea-db:
        condition: service_healthy
    restart: unless-stopped

  gitea-db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${GITEA_DB_ROOT_PASSWORD:-GiteaRootPassword123!}
      - MARIADB_DATABASE=${GITEA_DB_NAME:-gitea}
      - MARIADB_USER=${GITEA_DB_USER:-gitea}
      - MARIADB_PASSWORD=${GITEA_DB_PASSWORD:-GiteaPassword123!}
    volumes:
      - gitea-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p${GITEA_DB_ROOT_PASSWORD:-GiteaRootPassword123!} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:
  portainer-data:
  gitea-data:
  gitea-db-data: