name: cia-wow

services:
  # Dozzle - Logs en temps réel avec interface web
  dozzle:
    image: amir20/dozzle:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.dozzle.rule=Host(`logs.localhost`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      DOZZLE_ENABLE_ACTIONS: true
    networks:
      - traefik
    restart: unless-stopped

  # Jaeger - Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_ENABLED: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.jaeger.rule=Host(`jaeger.localhost`)
      - traefik.http.routers.jaeger.entrypoints=websecure
      - traefik.http.routers.jaeger.tls=true
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
    networks:
      - traefik
    restart: unless-stopped

  # AlertManager - Gestion des alertes
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.alertmanager.rule=Host(`alerts.localhost`)
      - traefik.http.routers.alertmanager.entrypoints=websecure
      - traefik.http.routers.alertmanager.tls=true
      - traefik.http.services.alertmanager.loadbalancer.server.port=9093
    networks:
      - traefik
      - prometheus
    restart: unless-stopped

volumes:
  alertmanager-data:

networks:
  traefik:
    external: true
  prometheus:
    external: true