#cloud-config
package_update: true
package_upgrade: false

packages:
  - python3
  - python3-pip
  - curl
  - wget

runcmd:
  - echo "VM ready for Ansible provisioning" > /tmp/vm-ready
  - chmod 644 /tmp/vm-ready